[package]
name = "fable-raytracer"
version = "0.1.0"
edition = "2021"

#[lib]
#name = "fable_raytracer"
#path = "src/lib.rs"
#crate-type = ["cdylib"]

[[bin]]
name = "fable_raytracer"
path = "src/main.rs"

[dependencies]
fable_library_rust = { path = "./fable_modules/fable-library-rust" }
#wasm-bindgen = "0.2"

[profile.release]
opt-level = 3
lto = "thin"

[profile.release-lto]
inherits = "release"
lto = true
